from __future__ import annotations

import pandas as pd
import streamlit as st

from kharvunic.collision import find_collisions
from kharvunic.diagnostic_runner import run_diagnostics
from kharvunic.domains import load_domains, suggest_domains
from kharvunic.evolution_v2 import EvolutionEngineV2
from kharvunic.history import load_history
from kharvunic.workflows import find_existing_entry, load_dictionary_v2, save_word_entry

REGISTERS = ['temple', 'boardroom', 'trade']
REGISTER_LABELS = {
    'temple': 'Temple Common',
    'boardroom': 'Boardroom Common',
    'trade': 'Trade Common',
}
HEALTH_ICON = {
    'passing': 'OK',
    'weak': 'WEAK',
    'failing': 'FAIL',
}

st.set_page_config(page_title='Kharvunic Workbench v2', layout='wide')


@st.cache_resource
def get_engine() -> EvolutionEngineV2:
    return EvolutionEngineV2()


@st.cache_data
def get_domain_options() -> list[str]:
    try:
        domains = load_domains()['domain'].dropna().astype(str).tolist()
    except Exception:
        domains = []
    return sorted(set(domain for domain in domains if domain))


def trace_forms(result: dict) -> list[str]:
    forms: list[str] = []
    for step in result['trace']:
        if not forms or forms[-1] != step.form:
            forms.append(step.form)
    return forms


def lineage_text(result: dict) -> str:
    return ' → '.join(trace_forms(result))


def trace_table(result: dict) -> pd.DataFrame:
    rows = []
    previous = ''
    for index, step in enumerate(result['trace']):
        rows.append({
            'step': index,
            'stage': step.stage,
            'form': step.form,
            'changed': index == 0 or step.form != previous,
            'rule / explanation': step.note,
        })
        previous = step.form
    return pd.DataFrame(rows)


def diagnostics_text(result: dict) -> str:
    warnings = result['diagnostics'].get('warnings', [])
    if not warnings:
        return 'No warnings.'
    return '; '.join(warnings)


def render_diagnostic_banner(result: dict) -> None:
    diagnostics = result['diagnostics']
    health = diagnostics.get('health', 'weak')
    warnings = diagnostics.get('warnings', [])
    source = result['source'].strip().lower()
    final = result['result'].strip().lower()

    if source == final or health == 'failing':
        st.error(
            'This form did not meaningfully evolve. The current rule set is insufficient for this root/register.'
        )
    elif health == 'weak' or warnings:
        st.warning('Weak evolution: ' + diagnostics_text(result))
    else:
        st.success('Evolution looks healthy: multiple meaningful v2 rules fired and the final form diverged.')


def result_summary_rows(results: dict[str, dict]) -> pd.DataFrame:
    return pd.DataFrame([
        {
            'register': REGISTER_LABELS[register],
            'final_form': result['result'],
            'ipa': result['ipa'],
            'health': result['diagnostics'].get('health', 'weak'),
            'rules_fired': len(result['rules_fired']),
            'source_similarity': result['diagnostics']['source_similarity'],
            'warnings': diagnostics_text(result),
        }
        for register, result in results.items()
    ])


def render_lineage(result: dict) -> None:
    st.markdown(f"**Lineage:** `{lineage_text(result)}`")
    st.dataframe(trace_table(result), use_container_width=True, hide_index=True)


def default_notes(result: dict) -> str:
    rules = ', '.join(result['rules_fired']) or 'no mechanical rules fired'
    notes = [
        'generated by v2 workbench',
        f"mechanical_result={result['mechanical_result']}",
        f"rules={rules}",
        f"health={result['diagnostics'].get('health', 'unknown')}",
    ]
    if result['override_applied']:
        notes.append(f"override={result['override_reason']}")
    warnings = diagnostics_text(result)
    if warnings != 'No warnings.':
        notes.append(f"diagnostics={warnings}")
    return '; '.join(notes)


def render_result(result: dict) -> None:
    render_diagnostic_banner(result)

    c1, c2, c3, c4 = st.columns(4)
    c1.metric('Final form', result['result'])
    c2.metric('IPA', result['ipa'])
    c3.metric('Rules fired', len(result['rules_fired']))
    c4.metric('Health', HEALTH_ICON.get(result['diagnostics'].get('health'), 'CHECK'))

    if result['override_applied']:
        st.info(f"Override applied: {result['override_reason']}")

    render_lineage(result)


def render_save_panel(result: dict, default_meaning: str, key_prefix: str) -> None:
    st.subheader('Save final v2 form')

    existing = find_existing_entry(result['result'], result['register'])
    if existing:
        st.error('Collision: this final form already exists in the same register. Review before saving.')
        st.dataframe(pd.DataFrame(existing), use_container_width=True, hide_index=True)

    dictionary = load_dictionary_v2()
    near_collisions = find_collisions(dictionary.to_dict(orient='records'), result['result'])
    if near_collisions:
        st.warning('Possible near-collisions in the dictionary:')
        st.dataframe(pd.DataFrame(near_collisions), use_container_width=True, hide_index=True)

    domain_options = get_domain_options()
    suggestions = suggest_domains(default_meaning)
    suggested = suggestions[0] if suggestions else ''
    options = [''] + domain_options
    suggested_index = options.index(suggested) if suggested in options else 0

    with st.form(f'{key_prefix}_save_form'):
        meaning = st.text_input('Meaning', value=default_meaning, key=f'{key_prefix}_meaning')
        domain = st.selectbox(
            'Semantic domain',
            options=options,
            index=suggested_index,
            key=f'{key_prefix}_domain',
            help='Required. This is written to data/dictionary.csv.',
        )
        notes = st.text_area('Notes', value=default_notes(result), key=f'{key_prefix}_notes')
        acknowledged = True
        if existing:
            acknowledged = st.checkbox(
                'I understand this will replace the existing entry and record the previous form in history.',
                key=f'{key_prefix}_ack_collision',
            )
        submitted = st.form_submit_button('Save to dictionary')

    if not submitted:
        return

    if existing and not acknowledged:
        st.error('Not saved. Confirm the collision warning before replacing an existing entry.')
        return

    if not domain:
        st.error('Not saved. Choose a semantic domain so the dictionary entry is complete.')
        return

    saved = save_word_entry(
        word=result['result'],
        ipa=result['ipa'],
        register=result['register'],
        meaning=meaning,
        source_root=result['source'],
        domain=domain,
        notes=notes,
        reason='saved through v2 workbench',
    )
    st.success(f"Saved {saved['word']} to data/dictionary.csv and recorded data/dictionary_history.csv.")


def evolve_page() -> None:
    st.header('Evolve one word')
    st.caption('Uses EvolutionEngineV2 and always shows lineage plus diagnostics.')

    with st.form('single_evolution_form'):
        source = st.text_input('Source Romance/Latin root', value='ambulare')
        meaning = st.text_input('Meaning', value='walk')
        register = st.selectbox('Register', options=REGISTERS, format_func=REGISTER_LABELS.get)
        submitted = st.form_submit_button('Evolve with v2 engine')

    if submitted:
        st.session_state['single_result'] = get_engine().evolve(source, register)
        st.session_state['single_meaning'] = meaning

    result = st.session_state.get('single_result')
    if result:
        render_result(result)
        render_save_panel(result, st.session_state.get('single_meaning', ''), 'single')


def compare_page() -> None:
    st.header('Compare registers')
    st.caption('Temple, Boardroom, and Trade forms are generated side by side with diagnostics for each.')

    with st.form('compare_form'):
        source = st.text_input('Source Romance/Latin root', value='misericordia')
        meaning = st.text_input('Meaning', value='mercy')
        submitted = st.form_submit_button('Compare all registers')

    if submitted:
        st.session_state['comparison'] = get_engine().compare(source)
        st.session_state['comparison_meaning'] = meaning

    comparison = st.session_state.get('comparison')
    if not comparison:
        return

    st.subheader('Register comparison')
    st.dataframe(result_summary_rows(comparison), use_container_width=True, hide_index=True)

    columns = st.columns(3)
    for column, register in zip(columns, REGISTERS):
        result = comparison[register]
        with column:
            st.markdown(f"### {REGISTER_LABELS[register]}")
            st.markdown(f"**{result['result']}**  ")
            st.caption(result['ipa'])
            render_diagnostic_banner(result)
            with st.expander('Lineage and rule explanations', expanded=True):
                render_lineage(result)

    st.subheader('Save one compared form')
    selected = st.selectbox(
        'Register to save',
        options=REGISTERS,
        format_func=REGISTER_LABELS.get,
        key='comparison_save_register',
    )
    render_save_panel(comparison[selected], st.session_state.get('comparison_meaning', ''), f'comparison_{selected}')


def diagnostics_page() -> None:
    st.header('Diagnostics')
    st.caption('Diagnostic root corpus health: passing, weak, or failing by register.')

    if st.button('Refresh diagnostics'):
        st.cache_data.clear()

    results = run_diagnostics()
    counts = results['health'].value_counts().to_dict()

    c1, c2, c3 = st.columns(3)
    c1.metric('Passing', counts.get('passing', 0))
    c2.metric('Weak', counts.get('weak', 0))
    c3.metric('Failing', counts.get('failing', 0))

    st.dataframe(results, use_container_width=True, hide_index=True)

    flagged = results[results['health'] != 'passing']
    if not flagged.empty:
        st.subheader('Weak or failing roots')
        st.dataframe(flagged, use_container_width=True, hide_index=True)


def dictionary_page() -> None:
    st.header('Dictionary')
    st.caption('Current canonical dictionary and save history.')

    df = load_dictionary_v2()
    query = st.text_input('Search dictionary')
    if query:
        q = query.lower()
        df = df[
            df['word'].str.lower().str.contains(q, na=False)
            | df['meaning'].str.lower().str.contains(q, na=False)
            | df['source_root'].str.lower().str.contains(q, na=False)
            | df['domain'].str.lower().str.contains(q, na=False)
        ]

    st.dataframe(df.sort_values(['register', 'word']), use_container_width=True, hide_index=True)

    with st.expander('Dictionary save history'):
        st.dataframe(load_history(), use_container_width=True, hide_index=True)


PAGES = {
    'Evolve Word': evolve_page,
    'Compare Registers': compare_page,
    'Diagnostics': diagnostics_page,
    'Dictionary': dictionary_page,
}

st.title('Kharvunic Workbench v2')
st.caption('One coherent v2 app: serious engine by default, diagnostics visible, save workflow reliable.')

page_name = st.sidebar.radio('Workflow', list(PAGES.keys()))
st.sidebar.info('Primary launch command: streamlit run app.py')

PAGES[page_name]()
