import streamlit as st
from kharvunic.engine import Evolver
from kharvunic.ipa import to_ipa
from kharvunic.dictionary import load_dictionary, save_entry, fuzzy_search

st.title('Kharvunic Evolution Engine')

mode = st.sidebar.selectbox(
    'Mode',
    ['Evolve Word', 'Dictionary']
)

if mode == 'Evolve Word':
    word = st.text_input('Source Romance/Latin Root', 'misericordia')
    meaning = st.text_input('Meaning', 'mercy')

    register = st.selectbox(
        'Target Register',
        ['common', 'temple', 'boardroom', 'trade']
    )

    if st.button('Evolve'):
        e = Evolver()
        result = e.evolve(word, register)

        ipa = to_ipa(result['result'])

        st.subheader('Result')
        st.write(result['result'])

        st.subheader('IPA')
        st.write(ipa)

        st.subheader('Trace')
        for step in result['trace']:
            st.write(step)

        if st.button('Save to Dictionary'):
            save_entry(
                word=result['result'],
                ipa=ipa,
                register=register,
                meaning=meaning,
                source_root=word,
                notes='generated by engine'
            )
            st.success('Saved.')

elif mode == 'Dictionary':
    df = load_dictionary()

    search = st.text_input('Search')

    if search:
        df = fuzzy_search(df, search)

    sort_mode = st.selectbox(
        'Sort',
        ['A-Z', 'Z-A']
    )

    ascending = sort_mode == 'A-Z'

    df = df.sort_values('word', ascending=ascending)

    st.dataframe(df, use_container_width=True)
